version: "3.8"

services:
  app:
    build: .
    container_name: movie-recommender-container
    ports:
      - "8000:8000"
    
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]